version: 2

sources:
  - name: raw
    database: academy
    schema: jsgomez14
    tables:
      - name: sneakers_catalog_cleaned_sneakers
      - name: sneakers_twitter_sentiment_analysis
      - name: incremental_sneakers_twitter_sentiment_analysis

    # freshness:
    #   warn_after:
    #     count: 1
    #     period: day
    #   error_after:
    #     count: 7
    #     period: day
    # loaded_at_field: "cast(last_updated_dt as timestamp)"